UPDATE Civilization_Religions 
SET ReligionType = 'RELIGION_ANGAKKUQISM'
WHERE CivilizationType = 'CIVILIZATION_VIVALA_DORSET'
AND EXISTS (SELECT * FROM Religions WHERE Type = 'RELIGION_ANGAKKUQISM');