-- Insert SQL Rules Here 
--==========================================================================================================================
-- DecisionsAddin_Support
--==========================================================================================================================
CREATE TABLE IF NOT EXISTS DecisionsAddin_Support(FileName);
INSERT INTO DecisionsAddin_Support (FileName) VALUES ('WabanakiDecisions.lua');
--==========================================================================================================================

insert into Language_en_US (Tag, Text)
values ('TXT_KEY_DECISIONS_CLWABANAKICONVERSION_NO_NAME', 'Declare a foreign religion to be the truth'),
	   ('TXT_KEY_DECISIONS_CLWABANAKICONVERSION_NO_DESC', 'Our leader, Henri Membertou, believes that the next revelation of our beliefs will come from across the seas. We shall embrace this new belief as our own![NEWLINE]Requirement/Restrictions:[NEWLINE][ICON_BULLET]Player must be the Wabanaki[NEWLINE][ICON_BULLET]At least one follower of a foreign religion in one of your cities.[NEWLINE][ICON_BULLET]May only be enacted once per game.[NEWLINE]Costs:[NEWLINE][ICON_BULLET]1 [ICON_MAGISTRATES] Magistrate[NEWLINE][ICON_BULLET]All of your population converts to the foreign religion.[NEWLINE]Rewards:[NEWLINE][ICON_BULLET]Whenever the founder of the foreign religion gains a Social Policy, gain one third of that Policy''s cost in [ICON_CULTURE] Culture.[NEWLINE][ICON_BULLET]Whenever the founder of the foreign religion gains a Great Person, gain a surge of [ICON_PEACE] Faith.'),
	   ('TXT_KEY_DECISIONS_CLWABANAKICONVERSION_NAME', 'Declare {1_Rel} to be the truth.'),
	   ('TXT_KEY_DECISIONS_CLWABANAKICONVERSION_DESC', 'Our leader, Henri Membertou, believes that {1_Rel} is the next revelation of our beliefs. We should embrace the religion of {1_Rel} as our own, and send a pilgrimage to {3_City}![NEWLINE]Requirement/Restrictions:[NEWLINE][ICON_BULLET]Player must be the Wabanaki[NEWLINE][ICON_BULLET]At least one follower of {1_Rel} in one of your cities.[NEWLINE][ICON_BULLET]May only be enacted once per game.[NEWLINE]Costs:[NEWLINE][ICON_BULLET]1 [ICON_MAGISTRATES] Magistrate[NEWLINE][ICON_BULLET]All of your population converts to {1_Rel}[NEWLINE]Rewards:[NEWLINE][ICON_BULLET]Whenever the {2_Found} gains a Social Policy, gain one third of that Policy''s cost in [ICON_CULTURE] Culture.[NEWLINE][ICON_BULLET]Whenever {2_Found} gains a Great Person, gain a surge of [ICON_PEACE] Faith.'),
	   ('TXT_KEY_DECISIONS_CLWABANAKICONVERSION_ADOPTED', 'Rewards:[NEWLINE][ICON_BULLET]Whenever the {2_Found} gains a Social Policy, gain one third of that Policy''s cost in [ICON_CULTURE] Culture.[NEWLINE][ICON_BULLET]Whenever {2_Found} gains a Great Person, gain a surge of [ICON_PEACE] Faith.'),
	   ('TXT_KEY_DECISIONS_CLWABANAKISPORTS_NAME', 'Promote our Winter Games'),
	   ('TXT_KEY_DECISIONS_CLWABANAKISPORTS_DESC', 'The people of the world seek something to distract them from their sorrows. Let us use the media to promote an International Oochamadyk League as a method of promoting national pride and bolstering the economy![NEWLINE]Requirement/Restrictions:[NEWLINE][ICON_BULLET]Player must be the Wabanaki[NEWLINE][ICON_BULLET]Must have at least 3 Broadcast towers in cities working Tundra or Snow tiles.[NEWLINE]Costs:[NEWLINE][ICON_BULLET]1200 [ICON_GOLD] Gold[NEWLINE]Rewards:[NEWLINE][ICON_BULLET]Whenever a player starts a golden age, gain [ICON_GOLD] Gold and [ICON_GOLDEN_AGE] Golden Age Points.[NEWLINE][ICON_BULLET]Gain more [ICON_GOLD] Gold and [ICON_GOLDEN_AGE] Golden Age points from civilizations as your culture eclipses theirs.'),
	   ('TXT_KEY_DECISIONS_CLWABANAKISPORTS_ENACTED', 'Rewards:[NEWLINE][ICON_BULLET]Whenever a player starts a golden age, gain [ICON_GOLD] Gold and [ICON_GOLDEN_AGE] Golden Age Points.[NEWLINE][ICON_BULLET]Gain more [ICON_GOLD] Gold and [ICON_GOLDEN_AGE] Golden Age points from civilizations as your culture eclipses theirs.');

