-------------------------------------------
--Building (Hulubalang)
-------------------------------------------
INSERT INTO Units
		(Type,					Description,					Civilopedia,								Strategy,								Help,								Cost,	PurchaseOnly,	MoveAfterPurchase,	Moves,	BaseSightRange,	Class,		Special,	Domain,		CivilianAttackPriority,	DefaultUnitAI,		AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	WorkRate,	UnitArtInfo,					UnitArtInfoEraVariation,	DontShowYields,	ShowInPedia,	MoveRate,	UnitFlagIconOffset,	PortraitIndex,	IconAtlas,					UnitFlagAtlas)
SELECT	'UNIT_JWW_HULUBALANG',	'TXT_KEY_UNIT_JWW_HULUBALANG',	'TXT_KEY_CIV5_UNIT_JWW_HULUBALANG_TEXT',	'TXT_KEY_UNIT_JWW_HULUBALANG_STRATEGY',	'TXT_KEY_UNIT_HELP_JWW_HULUBALANG',	275,	1,				1,					Moves,	BaseSightRange,	Class,		Special,	Domain,		CivilianAttackPriority,	DefaultUnitAI,		AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	WorkRate,	'ART_DEF_UNIT_JWW_HULUBALANG',	UnitArtInfoEraVariation,	DontShowYields,	ShowInPedia,	MoveRate,	0,					4,				'JWW_MALACCA_COLOR_ATLAS',	'JWW_MALACCA_UNIT_ALPHA_ATLAS_2'
FROM Units WHERE Type = 'UNIT_GREAT_GENERAL';

INSERT INTO UnitGameplay2DScripts
		(UnitType,				SelectionSound,		FirstSelectionSound)
SELECT	'UNIT_JWW_HULUBALANG',	SelectionSound,		FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO Unit_AITypes
		(UnitType,				UnitAIType)
SELECT	'UNIT_JWW_HULUBALANG',	UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO Unit_Builds
		(UnitType,				BuildType)
SELECT	'UNIT_JWW_HULUBALANG',	BuildType
FROM Unit_Builds WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JWW_HULUBALANG',		PromotionType
FROM Unit_FreePromotions WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO Unit_Flavors
		(UnitType,					FlavorType,			Flavor)
SELECT	'UNIT_JWW_HULUBALANG',		FlavorType,			Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO UnitPromotions_CivilianUnitType
		(PromotionType,		UnitType)
SELECT	PromotionType,		'UNIT_JWW_HULUBALANG'
FROM UnitPromotions_CivilianUnitType WHERE UnitType = 'UNIT_GREAT_GENERAL';

INSERT INTO Unit_UniqueNames
		(UnitType,				UniqueName)
VALUES	('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_TUN_TEMPURUNG'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_BADANG'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_TUN_HAMZAH'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_JEBAT'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_TUN_PERAK'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_ABU_BAKAR'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_WIKRAMA_WIRA'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_TUAH'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_KASTURI'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_LEKIR'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_ALI'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_ISKANDAR'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_HASAN'),
		('UNIT_JWW_HULUBALANG',	'TXT_KEY_JWW_HULUBALANG_HANG_HUSAIN');
-------------------------------------------
--Unit (Orang Laut)
-------------------------------------------
INSERT INTO Units
		(Type,					Description,					Civilopedia,								Strategy,								Help,								Combat,		RangedCombat,	Cost,	Moves,	Range,	BaseSightRange,	Class,		CombatClass,	Domain,		DefaultUnitAI,		MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	PrereqTech,		ObsoleteTech,		AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	UnitArtInfo,					ShowInPedia,	MoveRate,	UnitFlagIconOffset,	PortraitIndex,	IconAtlas,					UnitFlagAtlas)
SELECT	'UNIT_JWW_ORANG_LAUT',	'TXT_KEY_UNIT_JWW_ORANG_LAUT',	'TXT_KEY_CIV5_UNIT_JWW_ORANG_LAUT_TEXT',	'TXT_KEY_UNIT_JWW_ORANG_LAUT_STRATEGY',	'TXT_KEY_UNIT_HELP_JWW_ORANG_LAUT',	12,			13,				Cost,	Moves,	Range,	BaseSightRange,	Class,		CombatClass,	Domain,		DefaultUnitAI,		MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	PrereqTech,		ObsoleteTech,		AdvancedStartCost,	MinAreaSize,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	'ART_DEF_UNIT_JWW_ORANG_LAUT',	ShowInPedia,	MoveRate,	0,					2,				'JWW_MALACCA_COLOR_ATLAS',	'JWW_MALACCA_UNIT_ALPHA_ATLAS'
FROM Units WHERE Type = 'UNIT_GALLEASS';

INSERT INTO UnitGameplay2DScripts
		(UnitType,				SelectionSound,		FirstSelectionSound)
SELECT	'UNIT_JWW_ORANG_LAUT',	SelectionSound,		FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_GALLEASS';

INSERT INTO Unit_AITypes
		(UnitType,				UnitAIType)
SELECT	'UNIT_JWW_ORANG_LAUT',	UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_GALLEASS';

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
SELECT	'UNIT_JWW_ORANG_LAUT',		PromotionType
FROM Unit_FreePromotions WHERE UnitType = 'UNIT_GALLEASS';

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
VALUES	('UNIT_JWW_ORANG_LAUT',		'PROMOTION_BOARDING_PARTY_1'),
		('UNIT_JWW_ORANG_LAUT',		'PROMOTION_BOARDING_PARTY_2');

INSERT INTO Unit_Flavors
		(UnitType,					FlavorType,			Flavor)
SELECT	'UNIT_JWW_ORANG_LAUT',		FlavorType,			Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_GALLEASS';

INSERT INTO Unit_ClassUpgrades
		(UnitType,					UnitClassType)
SELECT	'UNIT_JWW_ORANG_LAUT',		UnitClassType
FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_GALLEASS';

INSERT INTO UnitPromotions
		(Type,								Description,							Help,										Sound,				CombatPercent,	CannotBeChosen,	PortraitIndex,	IconAtlas,			PediaType,		PediaEntry)
VALUES	('PROMOTION_JWW_ORANG_TRADE',		'TXT_KEY_PROMOTION_JWW_ORANG_TRADE',	'TXT_KEY_PROMOTION_JWW_ORANG_TRADE_HELP',	'AS2D_IF_LEVELUP',	33,				1,				59,				'PROMOTION_ATLAS',	'PEDIA_NAVAL',	'TXT_KEY_PROMOTION_JWW_ORANG_TRADE');

-------------------------------------------
--Leader (Parameswara)
-------------------------------------------

INSERT INTO Leaders
		(Type,						Description,						Civilopedia,							CivilopediaTag,									ArtDefineTag,				VictoryCompetitiveness,	WonderCompetitiveness,	MinorCivCompetitiveness,	Boldness,	DiploBalance,	WarmongerHate,	WorkAgainstWillingness,	WorkWithWillingness,	DenounceWillingness,	DoFWillingness,	Loyalty,	Neediness,	Forgiveness,	Chattiness,	Meanness,	PortraitIndex,	IconAtlas)
VALUES	('LEADER_JWW_PARAMESWARA',	'TXT_KEY_LEADER_JWW_PARAMESWARA',	'TXT_KEY_LEADER_JWW_PARAMESWARA_PEDIA',	'TXT_KEY_CIVILOPEDIA_LEADERS_JWW_PARAMESWARA',	'ParameswaraScene.xml',		4,						7,						1,							6,			9,				8,				2,						7,						8,						10,				8,			5,			1,				6,			1,			0,				'JWW_MALACCA_COLOR_ATLAS');

INSERT INTO Leader_MajorCivApproachBiases
		(LeaderType,				MajorCivApproachType,				Bias)
VALUES	('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_WAR',			3),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_HOSTILE',		4),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_DECEPTIVE',		9),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_GUARDED',		6),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_AFRAID',		6),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_FRIENDLY',		9),
		('LEADER_JWW_PARAMESWARA',	'MAJOR_CIV_APPROACH_NEUTRAL',		0);

INSERT INTO Leader_MinorCivApproachBiases
		(LeaderType,				MinorCivApproachType,				Bias)
VALUES	('LEADER_JWW_PARAMESWARA',	'MINOR_CIV_APPROACH_IGNORE',		1),
		('LEADER_JWW_PARAMESWARA',	'MINOR_CIV_APPROACH_FRIENDLY',		8),
		('LEADER_JWW_PARAMESWARA',	'MINOR_CIV_APPROACH_PROTECTIVE',	4),
		('LEADER_JWW_PARAMESWARA',	'MINOR_CIV_APPROACH_CONQUEST',		2),
		('LEADER_JWW_PARAMESWARA',	'MINOR_CIV_APPROACH_BULLY',			3);

INSERT INTO	Leader_Flavors
		(LeaderType,			FlavorType,								Flavor)
VALUES	('LEADER_JWW_PARAMESWARA',	'FLAVOR_OFFENSE',					4),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_DEFENSE',					9),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_CITY_DEFENSE',				10),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_MILITARY_TRAINING',			6),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_RECON',						5),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_RANGED',					4),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_MOBILE',					4),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_NAVAL',						9),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_NAVAL_RECON',				10),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_NAVAL_GROWTH',				8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_NAVAL_TILE_IMPROVEMENT',	7),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_AIR',						5),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_EXPANSION',					7),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_GROWTH',					6),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_TILE_IMPROVEMENT',			2),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_INFRASTRUCTURE',			5),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_PRODUCTION',				2),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_GOLD',						8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_SCIENCE',					2),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_CULTURE',					3),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_HAPPINESS',					8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_GREAT_PEOPLE',				7),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_WONDER',					8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_RELIGION',					6),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_DIPLOMACY',					10),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_SPACESHIP',					1),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_WATER_CONNECTION',			6),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_NUKE',						8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_USE_NUKE',					2),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_ESPIONAGE',					8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_ANTIAIR',					7),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_AIR_CARRIER',				7),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_ARCHAEOLOGY',				5),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_I_LAND_TRADE_ROUTE',		3),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_I_SEA_TRADE_ROUTE',			10),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_I_TRADE_ORIGIN',			6),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_I_TRADE_DESTINATION',		8),
		('LEADER_JWW_PARAMESWARA',	'FLAVOR_AIRLIFT',					2);

INSERT INTO Leader_Traits
		(LeaderType,				TraitType)
VALUES	('LEADER_JWW_PARAMESWARA',	'TRAIT_JWW_SULALATUS_SALATIN');

-------------------------------------------
--Trait (Sulalatus Salatin)
-------------------------------------------

INSERT INTO Traits
		(Type,							Description,							ShortDescription)
VALUES	('TRAIT_JWW_SULALATUS_SALATIN',	'TXT_KEY_TRAIT_JWW_SULALATUS_SALATIN',	'TXT_KEY_TRAIT_JWW_SULALATUS_SALATIN_SHORT');
-------------------------------------------
--Diplomacy Responses
-------------------------------------------

INSERT INTO Diplomacy_Responses
		(LeaderType,				ResponseType,									Response,																Bias)
VALUES	('LEADER_JWW_PARAMESWARA',	'RESPONSE_DEFEATED',							'TXT_KEY_LEADER_JWW_PARAMESWARA_DEFEATED%',								1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_EXPANSION_SERIOUS_WARNING',			'TXT_KEY_LEADER_JWW_PARAMESWARA_EXPANSION_SERIOUS_WARNING%',			1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_FIRST_GREETING',						'TXT_KEY_LEADER_JWW_PARAMESWARA_FIRSTGREETING%',						1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_GREETING_HOSTILE_HELLO',				'TXT_KEY_LEADER_JWW_PARAMESWARA_GREETING_HOSTILE_HELLO%',				1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_GREETING_NEUTRAL_HELLO',				'TXT_KEY_LEADER_JWW_PARAMESWARA_GREETING_NEUTRAL_HELLO%',				1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_GREETING_POLITE_HELLO',				'TXT_KEY_LEADER_JWW_PARAMESWARA_GREETING_POLITE_HELLO%',				1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',	'TXT_KEY_LEADER_JWW_PARAMESWARA_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',	1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_REQUEST',								'TXT_KEY_LEADER_JWW_PARAMESWARA_REQUEST%',								1),
		('LEADER_JWW_PARAMESWARA',	'RESPONSE_DECLAREWAR',							'TXT_KEY_LEADER_JWW_PARAMESWARA_DECLAREWAR%',							1);

-------------------------------------------
--Civilization (Malacca)
-------------------------------------------

INSERT INTO Civilizations
		(Type,							Description,					Civilopedia,						CivilopediaTag,				Playable,	AIPlayable,		ShortDescription,							Adjective,								DefaultPlayerColor,			ArtDefineTag,						ArtStyleType,		ArtStyleSuffix,		ArtStylePrefix,		PortraitIndex,	IconAtlas,					AlphaIconAtlas,				MapImage,			DawnOfManQuote,							DawnOfManImage)
VALUES	('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CIV_JWW_MALACCA_DESC',	'TXT_KEY_CIV_JWW_MALACCA_PEDIA',	'TXT_KEY_CIV5_JWW_MALACCA',	1,			1,				'TXT_KEY_CIV_JWW_MALACCA_SHORT_DESC',		'TXT_KEY_CIV_JWW_MALACCA_ADJECTIVE',	'PLAYERCOLOR_JWW_MALACCA',	'ART_DEF_CIVILIZATION_INDONESIA',	'ARTSTYLE_ASIAN',	'_ASIA',			'ASIAN',			1,				'JWW_MALACCA_COLOR_ATLAS',	'JWW_MALACCA_ALPHA_ATLAS',	'MalaccaMap.dds',	'TXT_KEY_CIV5_DAWN_JWW_MALACCA_TEXT',	'ParameswaraDOM.dds');

INSERT INTO Civilization_Leaders
		(CivilizationType,				LeaderheadType)
VALUES	('CIVILIZATION_JWW_MALACCA',	'LEADER_JWW_PARAMESWARA');

INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType,				UnitClassType,				UnitType)
VALUES	('CIVILIZATION_JWW_MALACCA',	'UNITCLASS_FRIGATE',		'UNIT_JWW_ORANG_LAUT'),
		('CIVILIZATION_JWW_MALACCA',	'UNITCLASS_GREAT_GENERAL',	'UNIT_JWW_HULUBALANG');

INSERT INTO Civilization_FreeBuildingClasses
		(CivilizationType,				BuildingClassType)
VALUES	('CIVILIZATION_JWW_MALACCA',	'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs
		(CivilizationType,				TechType)
VALUES	('CIVILIZATION_JWW_MALACCA',	'TECH_AGRICULTURE');

INSERT INTO Civilization_FreeUnits
		(CivilizationType,				UnitClassType,			UnitAIType,			Count)
VALUES	('CIVILIZATION_JWW_MALACCA',	'UNITCLASS_SETTLER',	'UNITAI_SETTLE',	1);

INSERT INTO Civilization_Religions
		(CivilizationType,				ReligionType)
VALUES	('CIVILIZATION_JWW_MALACCA',	'RELIGION_ISLAM');

INSERT INTO Civilization_Start_Along_Ocean
		(CivilizationType,					StartAlongOcean)
VALUES	('CIVILIZATION_JWW_MALACCA',	1);

INSERT INTO	Civilization_CityNames
		(CivilizationType,				CityName)
VALUES	('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_0'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_1'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_2'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_3'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_4'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_5'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_6'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_7'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_8'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_9'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_10'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_11'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_12'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_13'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_14'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_15'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_16'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_17'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_18'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_19'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_20'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_21'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_22'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_23'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_24'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_25'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_26'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_27'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_28'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_29'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_30'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_31'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_32'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_33'),
		('CIVILIZATION_JWW_MALACCA',	'TXT_KEY_CITY_NAME_JWW_MALACCA_34');
				
INSERT INTO Civilization_SpyNames
		(CivilizationType,					SpyName)
VALUES	('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_0'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_1'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_2'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_3'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_4'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_5'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_6'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_7'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_8'),
		('CIVILIZATION_JWW_MALACCA',		'TXT_KEY_SPY_NAME_JWW_MALACCA_9');

--================================================================
--================================================================
