--==========================================================================================================================	
-- CITIES
--==========================================================================================================================	

--------------------------------	
-- Civilization_CityNames
--------------------------------	
INSERT INTO Civilization_CityNames	
                 (CivilizationType,                              CityName)	
VALUES         ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_1'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_2'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_3'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_4'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_5'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_6'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_7'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_8'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_9'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_10'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_11'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_12'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_13'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_14'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_15'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_16'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_17'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_18'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_19'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_20'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_21'),	
                 ('CIVILIZATION_PG_RIODELAPLATA',   'TXT_KEY_CITY_NAME_CIVILIZATION_PG_RIODELAPLATA_22');
