INSERT INTO Religions 
			(Type,											       				Description,								     			 Civilopedia,					      IconAtlas,	 PortraitIndex,					        IconString)						   
VALUES		('RELIGION_FUJI_CULT_SM',			'TXT_KEY_RELIGION_FUJI_CULT_SM',			'TXT_KEY_RELIGION_FUJI_CULT_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				4,			'[ICON_RELIGION_FUJI_CULT_SM]'),
			('RELIGION_JODO_SHINSHU_SM',		'TXT_KEY_RELIGION_JODO_SHINSHU_SM',			'TXT_KEY_RELIGION_JODO_SHINSHU_SM_PEDIA',		'SM_JAPANESE_RELIGIONS_ATLAS',				5,			'[ICON_RELIGION_JODO_SHINSHU_SM]'),
			('RELIGION_KAMUI_SM',				'TXT_KEY_RELIGION_KAMUI_SM',				'TXT_KEY_RELIGION_KAMUI_SM_PEDIA',				'SM_JAPANESE_RELIGIONS_ATLAS',				10,			'[ICON_RELIGION_KAMUI_SM]'),
			('RELIGION_KOSHINTO_SM',			'TXT_KEY_RELIGION_KOSHINTO_SM',				'TXT_KEY_RELIGION_KOSHINTO_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				2,			'[ICON_RELIGION_KOSHINTO_SM]'),
			('RELIGION_NICHIREN_SM',			'TXT_KEY_RELIGION_NICHIREN_SM',				'TXT_KEY_RELIGION_NICHIREN_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				6,			'[ICON_RELIGION_NICHIREN_SM]'),
			('RELIGION_SHINGON_SM',				'TXT_KEY_RELIGION_SHINGON_SM',				'TXT_KEY_RELIGION_SHINGON_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				8,			'[ICON_RELIGION_SHINGON_SM]'),
			('RELIGION_SHUGENDO_SM',			'TXT_KEY_RELIGION_SHUGENDO_SM',				'TXT_KEY_RELIGION_SHUGENDO_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				3,			'[ICON_RELIGION_SHUGENDO_SM]'),
			('RELIGION_SOKA_SM',				'TXT_KEY_RELIGION_SOKA_SM',					'TXT_KEY_RELIGION_SOKA_SM_PEDIA',				'SM_JAPANESE_RELIGIONS_ATLAS',				13,			'[ICON_RELIGION_SOKA_SM]'),
			('RELIGION_STATE_SHINTO_SM',		'TXT_KEY_RELIGION_STATE_SHINTO_SM',			'TXT_KEY_RELIGION_STATE_SHINTO_SM_PEDIA',		'SM_JAPANESE_RELIGIONS_ATLAS',				1,			'[ICON_RELIGION_STATE_SHINTO_SM]'),
			('RELIGION_TENDAI_SM',				'TXT_KEY_RELIGION_TENDAI_SM',				'TXT_KEY_RELIGION_TENDAI_SM_PEDIA',				'SM_JAPANESE_RELIGIONS_ATLAS',				7,			'[ICON_RELIGION_TENDAI_SM]'),
			('RELIGION_TENRIKYO_SM',			'TXT_KEY_RELIGION_TENRIKYO_SM',				'TXT_KEY_RELIGION_TENRIKYO_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				12,			'[ICON_RELIGION_TENRIKYO_SM]'),
			('RELIGION_UTAKI_SM',				'TXT_KEY_RELIGION_UTAKI_SM',				'TXT_KEY_RELIGION_UTAKI_SM_PEDIA',				'SM_JAPANESE_RELIGIONS_ATLAS',				11,			'[ICON_RELIGION_UTAKI_SM]'),
			('RELIGION_YOSHIDA_SM',				'TXT_KEY_RELIGION_YOSHIDA_SM',				'TXT_KEY_RELIGION_YOSHIDA_SM_PEDIA',			'SM_JAPANESE_RELIGIONS_ATLAS',				0,			'[ICON_RELIGION_YOSHIDA_SM]'),
			('RELIGION_ZEN_SM',					'TXT_KEY_RELIGION_ZEN_SM',					'TXT_KEY_RELIGION_ZEN_SM_PEDIA',				'SM_JAPANESE_RELIGIONS_ATLAS',				9,			'[ICON_RELIGION_ZEN_SM]');

CREATE TRIGGER ReligionJaRCheck
AFTER INSERT ON Religions WHEN 'RELIGION_JUDAISM' = NEW.Type
BEGIN

	UPDATE Religions 
	SET Description = "TXT_KEY_RELIGION_SM_SHINTO"
	WHERE Type = "RELIGION_SHINTO";

	UPDATE Religions 
	SET Civilopedia = "TXT_KEY_RELIGION_SM_SHINTO_PEDIA"
	WHERE Type = "RELIGION_SHINTO";

END;
