INSERT INTO IconTextureAtlases 
			(Atlas, 									IconSize, 						 Filename,      IconsPerRow, IconsPerColumn)
VALUES		('SM_JAPANESE_RELIGIONS_ATLAS', 					 256,     'SM_JaR_Icons_256.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					 214, 	  'SM_JaR_Icons_214.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					 128, 	  'SM_JaR_Icons_128.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  80, 	   'SM_JaR_Icons_80.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  64, 	   'SM_JaR_Icons_64.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  48, 	   'SM_JaR_Icons_48.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  32, 	   'SM_JaR_Icons_32.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  24, 	   'SM_JaR_Icons_24.dds',				4, 				4),
			('SM_JAPANESE_RELIGIONS_ATLAS', 					  16, 	   'SM_JaR_Icons_16.dds',				4, 				4);

INSERT INTO IconFontTextures 
			(IconFontTexture, 											 IconFontTextureFile)
VALUES		('ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS', 					 'JaRFontIcons');

INSERT INTO IconFontMapping 
			(IconName, 													IconFontTexture,	 IconMapping)
VALUES		('ICON_RELIGION_FUJI_CULT_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			5),
			('ICON_RELIGION_JODO_SHINSHU_SM',		'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			6),
			('ICON_RELIGION_KAMUI_SM',				'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			11),
			('ICON_RELIGION_KOSHINTO_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			3),
			('ICON_RELIGION_NICHIREN_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			7),
			('ICON_RELIGION_SHINGON_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			9),
			('ICON_RELIGION_SHUGENDO_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			4),
			('ICON_RELIGION_SOKA_SM',				'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			14),
			('ICON_RELIGION_STATE_SHINTO_SM',		'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			2),
			('ICON_RELIGION_TENDAI_SM',				'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			8),
			('ICON_RELIGION_TENRIKYO_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			13),
			('ICON_RELIGION_UTAKI_SM',				'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			12),
			('ICON_RELIGION_YOSHIDA_SM',			'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			1),
			('ICON_RELIGION_ZEN_SM',				'ICON_FONT_TEXTURE_SM_JAPANESE_RELIGIONS',			10);