-----------------------------------------------------------------------------
-- Single Unit Graphics
-- R.E.D. Modpack (v 24) Compatibility
-----------------------------------------------------------------------------

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_CROSSBOWMAN_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_CROSSBOWMAN_IROQUOIS','ART_DEF_UNIT_MEMBER_CROSSBOWMAN_IROQUOIS_V4',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_HORSEMAN_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_HORSEMAN_IROQUOIS','ART_DEF_UNIT_MEMBER_HORSEMAN_IROQUOIS_V4',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_HORSEMAN_MED';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_HORSEMAN_MED','ART_DEF_UNIT_MEMBER_HORSEMAN',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_HORSEMAN_ROME';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_HORSEMAN_ROME','ART_DEF_UNIT_MEMBER_HORSEMAN_ROME_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_HORSEMAN_RUSSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_HORSEMAN_RUSSIA','ART_DEF_UNIT_MEMBER_HORSEMAN_RUSSIA_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_KNIGHT_FRANCE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_KNIGHT_FRANCE','ART_DEF_UNIT_MEMBER_KNIGHT_FRANCE_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_KNIGHT_INDIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_KNIGHT_INDIA','ART_DEF_UNIT_MEMBER_KNIGHT_INDIA_V4',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_KNIGHT_ROME';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_KNIGHT_ROME','ART_DEF_UNIT_MEMBER_KNIGHT_ROME_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_KNIGHT_RUSSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_KNIGHT_RUSSIA','ART_DEF_UNIT_MEMBER_KNIGHT_RUSSIA_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_BYZANTIUM';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_BYZANTIUM','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_BYZANTIUM_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_ENGLAND';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_ENGLAND','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_ENGLAND_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_FRANCE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_FRANCE','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_FRANCE_V4',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_GERMANY';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_GERMANY','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_GERMANY_V6',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_IROQUOIS','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_IROQUOIS_V3',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_RUSSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_RUSSIA','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_RUSSIA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_LONGSWORDSMAN_SWEDEN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_LONGSWORDSMAN_SWEDEN','ART_DEF_UNIT_MEMBER_LONGSWORDSMAN_SWEDEN_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_AMERICA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_AMERICA','ART_DEF_UNIT_MEMBER_RIFLEMAN_AMERICA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_AUSTRIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_AUSTRIA','ART_DEF_UNIT_MEMBER_RIFLEMAN_AUSTRIA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_AZTEC';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_AZTEC','ART_DEF_UNIT_MEMBER_RIFLEMAN_AZTEC_V3',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_EGYPT';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_EGYPT','ART_DEF_UNIT_MEMBER_RIFLEMAN_EGYPT_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_GREECE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_GREECE','ART_DEF_UNIT_MEMBER_RIFLEMAN_GREECE_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_IROQUOIS','ART_DEF_UNIT_MEMBER_RIFLEMAN_IROQUOIS_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_OTTOMAN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_OTTOMAN','ART_DEF_UNIT_MEMBER_RIFLEMAN_OTTOMAN_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_PERSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_PERSIA','ART_DEF_UNIT_MEMBER_RIFLEMAN_PERSIA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_RUSSIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_RUSSIA','ART_DEF_UNIT_MEMBER_RIFLEMAN_RUSSIA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_RIFLEMAN_SPAIN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_RIFLEMAN_SPAIN','ART_DEF_UNIT_MEMBER_RIFLEMAN_SPAIN_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SCOUT_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SCOUT_IROQUOIS','ART_DEF_UNIT_MEMBER_SCOUT_IROQUOIS_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SPEARMAN_IROQUOIS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN_IROQUOIS','ART_DEF_UNIT_MEMBER_SPEARMAN_IROQUOIS_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SPEARMAN_MAYA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN_MAYA','ART_DEF_UNIT_MEMBER_SPEARMAN_MAYA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SPEARMAN_MED';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN_MED','ART_DEF_UNIT_MEMBER_SPEARMAN_V3',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SPEARMAN_SPAIN';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SPEARMAN_SPAIN','ART_DEF_UNIT_MEMBER_SPEARMAN_SPAIN_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SWORDSMAN_BABYLON';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SWORDSMAN_BABYLON','ART_DEF_UNIT_MEMBER_SWORDSMAN_BABYLON_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_SWORDSMAN_INCA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_SWORDSMAN_INCA','ART_DEF_UNIT_MEMBER_SWORDSMAN_INCA_V2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_U_GREEK_HOPLITE';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_GREEK_HOPLITE','ART_DEF_UNIT_MEMBER_U_GREEK_HOPLITE',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT_U_JAPANESE_SAMURAI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT_U_JAPANESE_SAMURAI','ART_DEF_UNIT_MEMBER_U_JAPANESE_SAMURAI',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_POLYNESIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLYNESIA','ART_DEF_UNIT_MEMBER_EURODONKEY',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_AUSTRIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_AUSTRIA','ART_DEF_UNIT_MEMBER_WARRIOR_AUSTRIA_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_CELTS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_CELTS','ART_DEF_UNIT_MEMBER_WARRIOR_CELTS_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_DENMARK';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_DENMARK','ART_DEF_UNIT_MEMBER_WARRIOR_DENMARK_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_GERMANY';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_GERMANY','ART_DEF_UNIT_MEMBER_WARRIOR_GERMANY_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_NETHERLANDS';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_NETHERLANDS','ART_DEF_UNIT_MEMBER_WARRIOR_NETHERLANDS_V2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__WARRIOR_SONGHAI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__WARRIOR_SONGHAI','ART_DEF_UNIT_MEMBER_WARRIOR_SONGHAI_V2',"1");